### ISSUE TITLE
Support for closed days

### ISSUE THREAD

**Issue by magick93** [gnikolovski/commerce_shopping_hours#1]
Hello

Firstly, thanks for putting together this module.

I'm trying to set this up for a store, which is closed on Sundays. However, it seems this isnt possible.

![Selection_027](https://user-images.githubusercontent.com/2173213/81494316-0ca86d80-92fc-11ea-863d-e0cae08cdcdf.png)

Maybe it would be possible to integrate https://www.drupal.org/project/office_hours ?

**Comment by gnikolovski** [comment]
Fixed here: https://www.drupal.org/project/commerce_shopping_hours/issues/3136053
